// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    window.folderHandler = function() {
      return $('li.folder').click(function(e) {
        var currentState, path;
        path = $(this).attr('data-path');
        renderFolder(path);
        currentState = "" + location.pathname + "?path=" + path;
        return history.replaceState(currentState, currentState, currentState);
      });
    };
    window.fileHandler = function() {
      return $('li.file').click(function(e) {
        var path;
        path = $(this).attr('data-path');
        return goose.readFile(path, function(content) {
          var currentState;
          renderFile(path, content);
          currentState = "" + location.pathname + "?path=" + paht;
          return history.replaceState(currentState, currentState, currentState);
        });
      });
    };
    window.renderFolder = function(folder) {
      return goose.readDir(folder, function(files) {
        var file, fileNames, _i, _len;
        fileNames = [];
        for (_i = 0, _len = files.length; _i < _len; _i++) {
          file = files[_i];
          if (file.isFolder) {
            fileNames.push("<li class=\"folder\" data-path=\"" + file.path + "\">" + file.name + "</li>");
          } else {
            fileNames.push("<li class=\"file\" data-path=\"" + file.path + "\">" + file.name + "</li>");
          }
        }
        $('#sidebar').html("<ul>" + (fileNames.join('')) + "</ul>");
        return $('#content').html('');
      });
    };
    window.renderFile = function(file, content) {
      return $('#content').html(content);
    };
    window.load = function() {
      var href, path, query_params;
      if (location.href.endsWith('/')) {
        href = location.href.substring(0, location.href.length - 1);
        query_params = href.split('?')[1];
        if (query_params) {
          path = query_params.match(/path=([^#&]+)/)[1];
        } else {
          path = '/';
        }
        return renderFolder(path);
      } else {
        href = location.href;
        query_params = href.split('?')[1];
        if (query_params) {
          path = query_params.match(/path=([^#&]+)/)[1];
        } else {
          path = '/';
        }
        return renderFile(path);
      }
    };
    load();
    fileHandler();
    return folderHandler();
  });

}).call(this);
